baseURL = "https://zhangbin971.github.io/"
languageCode = "zh-CN"
title = "2021/07/24"

theme = "maupassant"

summaryLength = 20
uglyurls = true

[author]
name = "enenen"


[params]
localSearch = true
fancybox = true
busuanzi = true
relativeURLs = false
subtitle = "流水下滩非本意,白云出岫本无心!!!"

[taxonomies]
tag = "tags"
category = "categories"

